CREATE ROLE flyway LOGIN PASSWORD 'flyway_ps' SUPERUSER CREATEDB CREATEROLE REPLICATION;
CREATE ROLE example_api LOGIN PASSWORD 'example_api_ps' CREATEDB CREATEROLE INHERIT;
CREATE ROLE example_api_readonly LOGIN PASSWORD 'example_api_readonly_ps' CREATEDB CREATEROLE INHERIT;

CREATE DATABASE "example-api";
