CREATE ROLE flyway LOGIN PASSWORD 'flyway_ps' SUPERUSER CREATEDB CREATEROLE REPLICATION;
CREATE ROLE author_api LOGIN PASSWORD 'author_api_ps' CREATEDB CREATEROLE INHERIT;
CREATE ROLE author_api_readonly LOGIN PASSWORD 'author_api_readonly_ps' CREATEDB CREATEROLE INHERIT;

CREATE DATABASE "author-api";
