CREATE SCHEMA example;

ALTER ROLE example_api WITH NOCREATEDB NOCREATEROLE NOINHERIT;

GRANT USAGE ON SCHEMA example TO example_api;

ALTER DEFAULT PRIVILEGES IN SCHEMA example GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO example_api;
