CREATE SCHEMA author;

ALTER ROLE author_api WITH NOCREATEDB NOCREATEROLE NOINHERIT;

GRANT USAGE ON SCHEMA author TO author_api;

ALTER DEFAULT PRIVILEGES IN SCHEMA author GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO author_api;
