application:
  port: 5130
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
resources:
  limits:
    cpu: 150m
    memory: 150Mi
  requests:
    cpu: 100m
    memory: 128Mi
image:
  repository: 726234843960.dkr.ecr.us-east-2.amazonaws.com/author-api
  tag:
fullnameOverride: author-api
extraEnv:
  NODE_ENV: ""
  POSTGRES_DATABASE: "authorapidb"
  POSTGRES_USER: "author_api"
secrets:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_KEY: ""
  POSTGRES_PASSWORD: ""
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 15
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 15
